srcfile=open("file","w+")
srcfile.write("welcome to python programming\n")
srcfile.writelines(["hello world\n","hello karthik"])
srcfile.seek(0)
print(srcfile.read())
srcfile.seek(0)
print(srcfile.readline())
srcfile.seek(0)
print(srcfile.readlines())
